"""empty message

Revision ID: 0f8e7c7c440e
Revises: 8cb60a28ca13
Create Date: 2018-12-04 20:02:52.210858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8e7c7c440e'
down_revision = '8cb60a28ca13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count', sa.Column('currentCount', sa.Integer(), nullable=True, unique=False))
    op.drop_column('count', 'num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count', sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('count', 'currentCount')
    # ### end Alembic commands ###
