"""empty message

Revision ID: 4b7ae5557736
Revises: 
Create Date: 2018-12-04 10:52:20.332591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7ae5557736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count', sa.Column('currentCount', sa.Integer(), nullable=True))
    op.drop_column('count', 'num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count', sa.Column('num', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('count', 'currentCount')
    # ### end Alembic commands ###
