"""empty message

Revision ID: 6676a266f9b7
Revises: 
Create Date: 2018-12-03 16:09:25.670312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6676a266f9b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'paletteId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'paletteId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
