"""empty message

Revision ID: d71553f087ce
Revises: 
Create Date: 2018-12-04 14:01:10.792451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71553f087ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count',
    sa.Column('currentCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('currentCount')
    )
    op.alter_column('image', 'paletteId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'paletteId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('count')
    # ### end Alembic commands ###
