"""empty message

Revision ID: de56dcb3221d
Revises: 
Create Date: 2018-12-04 19:11:41.874513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de56dcb3221d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count',
    sa.Column('currentCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('currentCount')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count')
    # ### end Alembic commands ###
